language: python
python:
- '3.4'
install:
- pip install -r requirements.txt --use-mirrors
script:
- python manage.py test
notifications:
  webhooks: http://project-monitor.cf.18f.us/projects/mock-pay/status
